# Generated by Django 3.0.4 on 2020-03-20 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20200320_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
